from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from docx import Document as DocxDocument
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import Any, Dict
import io
from datetime import datetime


class ExportService:
    def __init__(self):
        self.styles = getSampleStyleSheet()
    
    async def export_summary(
        self,
        summary: Any,
        document: Any,
        format: str,
        include_keywords: bool = True,
        user: Any = None
    ) -> bytes:
        """Export summary to specified format"""
        
        if format == "pdf":
            return await self._export_pdf(summary, document, include_keywords, user)
        elif format == "docx":
            return await self._export_docx(summary, document, include_keywords, user)
        else:
            return await self._export_txt(summary, document, include_keywords, user)
    
    async def _export_pdf(self, summary, document, include_keywords, user) -> bytes:
        """Export to PDF using ReportLab"""
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.8*inch, bottomMargin=0.8*inch)
        
        story = []
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a73e8'),
            spaceAfter=30
        )
        story.append(Paragraph("Summary Report", title_style))
        
        meta_style = self.styles['Normal']
        story.append(Paragraph(f"Document: {document.original_filename}", meta_style))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", meta_style))
        story.append(Paragraph(f"Summary Type: {summary.summary_type}", meta_style))
        story.append(Paragraph(f"Summary Length: {summary.summary_length}", meta_style))
        story.append(Spacer(1, 20))
        
        content_style = ParagraphStyle(
            'Content',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12
        )
        
        if summary.summary_type == 'bullets':
            bullets = summary.summary_text.split('\n')
            for bullet in bullets:
                if bullet.strip():
                    clean_bullet = bullet.replace('•', '').strip()
                    story.append(Paragraph(f"• {clean_bullet}", content_style))
        else:
            paragraphs = summary.summary_text.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    story.append(Paragraph(para, content_style))
        
        if include_keywords and summary.keywords:
            story.append(Spacer(1, 20))
            story.append(Paragraph("Keywords", self.styles['Heading2']))
            keywords_text = ", ".join(summary.keywords[:10])
            story.append(Paragraph(keywords_text, content_style))
        
        story.append(Spacer(1, 30))
        footer_style = ParagraphStyle(
            'Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            alignment=1
        )
        story.append(Paragraph(f"Generated by AI Smart Summarizer", footer_style))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    async def _export_docx(self, summary, document, include_keywords, user) -> bytes:
        """Export to DOCX using python-docx"""
        
        doc = DocxDocument()
        
        title = doc.add_heading('Summary Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"Document: {document.original_filename}")
        doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        doc.add_paragraph(f"Summary Type: {summary.summary_type}")
        doc.add_paragraph(f"Summary Length: {summary.summary_length}")
        doc.add_paragraph()
        
        doc.add_heading('Summary', level=1)
        
        if summary.summary_type == 'bullets':
            bullets = summary.summary_text.split('\n')
            for bullet in bullets:
                if bullet.strip():
                    clean_bullet = bullet.replace('•', '').replace('-', '').strip()
                    doc.add_paragraph(clean_bullet, style='List Bullet')
        else:
            paragraphs = summary.summary_text.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    doc.add_paragraph(para)
        
        if include_keywords and summary.keywords:
            doc.add_page_break()
            doc.add_heading('Keywords', level=1)
            keywords_text = ", ".join(summary.keywords[:10])
            doc.add_paragraph(keywords_text)
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
    
    async def _export_txt(self, summary, document, include_keywords, user) -> bytes:
        """Export to plain text"""
        
        lines = []
        lines.append("=" * 60)
        lines.append("SUMMARY REPORT")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Document: {document.original_filename}")
        lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        lines.append(f"Summary Type: {summary.summary_type}")
        lines.append(f"Summary Length: {summary.summary_length}")
        lines.append("")
        lines.append("-" * 60)
        lines.append("SUMMARY")
        lines.append("-" * 60)
        lines.append("")
        lines.append(summary.summary_text)
        
        if include_keywords and summary.keywords:
            lines.append("")
            lines.append("-" * 60)
            lines.append("KEYWORDS")
            lines.append("-" * 60)
            lines.append("")
            lines.append(", ".join(summary.keywords[:10]))
        
        lines.append("")
        lines.append("=" * 60)
        lines.append("Generated by AI Smart Summarizer")
        
        return "\n".join(lines).encode('utf-8')
    
    def get_mime_type(self, format: str) -> str:
        """Get MIME type for export format"""
        
        mime_types = {
            "pdf": "application/pdf",
            "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "txt": "text/plain"
        }
        return mime_types.get(format, "application/octet-stream")